### ISSUE TITLE
Error on loading FC with geomatics installed

### ISSUE THREAD

**Issue by luzpaz** [HakanSeven12/FreeCAD-Geomatics-Workbench#13]
```
Init:      Initializing /home/beast/.FreeCAD/Mod/Geomatics... failed
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 120, in InitApplications
  File "<string>", line 31, in <module>
  File "<string>", line 33, in GeomaticsWorkbench
  File "/home/foo/.FreeCAD/Mod/CADExchanger/Init.py", line 24, in <module>
    preferences = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/CADExchanger")
NameError: name 'FreeCAD' is not defined
----------------------------------------------------------------------------------------------------
During initialization the error name 'FreeCAD' is not defined occurred in /home/foo/.FreeCAD/Mod/Geomatics/InitGui.py
Please look into the log file for further information
```

OS: Manjaro Linux (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.17646 (Git) AppImage
Build type: Release
Branch: master
Hash: 641d946fa47573562026e042b1706759bd47611e
Python version: 3.7.3
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

**Comment by luzpaz** [comment]
Also 
```
During initialization the error name '__file__' is not defined occurred in /home/beast/.FreeCAD/Mod/Geomatics/Init.py
Please look into the log file for further information
Add Triangle Added
Delete Triangle Added
Swap Edge Added
Smooth Surface Added
Add Triangle Added
During initialization the error name 'FreeCAD' is not defined occurred in /home/beast/.FreeCAD/Mod/Geomatics/InitGui.py
Please look into the log file for further information
```

**Comment by HakanSeven12** [comment]
How you install the wb?

**Comment by luzpaz** [comment]
Via Addon Manager

**Comment by luzpaz** [comment]
Looks like the error is gone in the latest geomatic update
